FROM python:3.12.2-alpine3.19
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["python", "runner.py"]
# TODO - careful! might need to create db tables and migrate first for the first time
