FROM python:3.12.2-slim-bullseye
RUN apt-get update && apt-get -y install libpq-dev gcc
WORKDIR /app
COPY requirements-prod.txt requirements-prod.txt
RUN pip install -r requirements-prod.txt
COPY . .
EXPOSE 8510
CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:8510", "runner:app"]
