"""user on delete cascade

Revision ID: 776dc9818856
Revises: 5d11375faec2
Create Date: 2024-03-14 19:59:32.718389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776dc9818856'
down_revision = '5d11375faec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_task_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_task_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
