"""empty message

Revision ID: a50e878828ec
Revises: 61d48ace0c0b
Create Date: 2024-03-14 18:57:47.778225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50e878828ec'
down_revision = '61d48ace0c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
