name: Deploy Backend Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker image and push to Docker hub
        working-directory: ./backend
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t michac789/taskmaster_backend_prod:latest -f Dockerfile.prod .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push michac789/taskmaster_backend_prod:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_SSH_USER }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          script: |
            docker stop taskmaster_backend
            docker rm taskmaster_backend
            docker rmi michac789/taskmaster_backend_prod:latest
            docker pull michac789/taskmaster_backend_prod:latest
            docker run -d -p 8510:8510 --name taskmaster_backend michac789/taskmaster_backend_prod:latest
          