name: Run Backend Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.2'

      - name: Install dependencies
        working-directory: ./backend
        run: pip install -r requirements.txt
        
      - name: Run tests
        working-directory: ./backend
        run: python -m unittest tests
